### PR TITLE
Merge branch Develop to Master 

### PR DESCRIPTION
**Pull request by luongdinhkhanhvinh**

### CODE REVIEW

**Comment by jaanavrt** [comment]
Hello i paid for a app for a developer he developer app that has bugs. i need android developer to fix thoes bugs and make full qa on the app and upload it 
its simple job 
if u php core (no laravel) and android native freelancer and coding both and have a free time id be happy working with u . also if thos project will be good i will love to have a long term work with you by upgrading this app adding features u can make great money. waiting for ur replay !
need to fix existing dating script php bugs on web version and android app bugs. php core and android native  
i contacted u via github. also i can pay via paypal *

**Comment by jaanavrt** [comment]
DO U HAVE SKYPE?

**Comment by luongdinhkhanhvinh** [comment]
Yes, my Skype ID is :khanhvinh15 .If you are interested in our team, we can
exchange more via skype.

Vào Th 2, 10 thg 8, 2020 vào lúc 07:04 jaanavrt <notifications@github.com>
đã viết:

**Comment by luongdinhkhanhvinh** [comment]
Hi jaanavrt.
Thank you for your interest in our team products.If you are interested in
Native or PHP then you can contact via skype. My skype number is:
khanhvinh15
Best regards

Vào Th 2, 10 thg 8, 2020 vào lúc 07:04 jaanavrt <notifications@github.com>
đã viết:

**Pull request merged**
